[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/api/health"
interval = 30
timeout = 10
maxRetries = 3